from __future__ import division, print_function
import random
import string
from listogram import Listogram


class MarkovChain(dict):
    """MarkovChain represents a Markov chain implemented as a subclass of the dict type."""

    def __init__(self, word_list=None):
        """Initialize this Markov chain by learning from the given word list."""
        super(MarkovChain, self).__init__()  # Initialize as a new dictionary
        # Add properties to track useful counts for this Markov chain
        self.types = 0  # Count of distinct word types in this Markov chain
        self.tokens = 0  # Total count of all word tokens in this Markov chain
        # Learn from the given word list, if any
        if word_list is not None:
            self.learn(word_list)

    def learn(self, word_list):
        """Learn from the given word list by building the Markov chain."""
        # Loop through all words in the word list
        for i in range(len(word_list) - 1):
            # Keep track of the current word and the next word
            current_word = word_list[i]
            next_word = word_list[i + 1]
            # Check if the current word is already a key in the Markov chain
            if current_word in self:
                # Add the next word to the set of words following the current word
                self[current_word].add_count(next_word)
            # Otherwise, the current word is not in the Markov chain yet
            else:
                # Add the current word to the Markov chain and set an empty list as its value
                self[current_word] = Listogram([next_word])
                # Increment the types count
                self.types += 1
            # Increment the tokens count
            self.tokens += 1

    def random_walk(self, start_word, num_words):
        """Perform a random walk on this Markov chain starting from the given word."""
        # Start with the given start word
        walk = [start_word]
        # Loop until we've produced the given number of words
        for _ in range(num_words - 1):
            # Get the next word list from the end of the walk
            current_word = walk[-1]
            # Check if the current word is a key in the Markov chain
            if current_word in self:
                # If so, get a random next word from the current word's list
                next_word = self[current_word].sample()
                # Add the next word to the end of the walk
                walk.append(next_word)
            # If not, we've reached the end of the chain, so break
            else:
                break
        # Add capitalization to the first word
        walk[0] = walk[0].capitalize()
        # Return the walk as a string
        return walk


def generate_random_sentence(chain, start_word, num_words):
    """Print samples generated by performing a random walk on the given Markov chain."""
    samples = chain.random_walk(start_word, num_words)

    # Check if the start word is lowercase
    if start_word[0].islower():
        start_word = start_word.capitalize()

    # Read the source text file and process it
    text_file = "little_women.txt"
    source_text = open(text_file, "r").read()
    translator = str.maketrans("", "", string.punctuation + "“”‘’")

    # Remove punctuations and split into words
    word_list = source_text.translate(translator).split()

    # Learn from the processed word list
    chain.learn(word_list)

    capitalized_samples = [samples[0].capitalize()] + samples[1:]
    print('Random walk ({} words) beginning with the word "{}":'.format(num_words, start_word))
    print(' '.join(capitalized_samples) + '.')


def main():
    # Test the Markov chain on words in a classic book title
    text_file = "little_women.txt"
    source_text = open(text_file, "r").read()
    translator = str.maketrans("", "", string.punctuation + "“”‘’")

    # remove punctuations and split into words
    word_list = source_text.translate(translator).split()
    chain = MarkovChain(word_list)
    start_word = random.choice(word_list)
    num_words = 18

    return generate_random_sentence(chain, start_word, num_words)


if __name__ == '__main__':
    main()
